name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'branch/tag/commit id'
        required: true

jobs:
  set_environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.env.outputs.env }}
    steps:
      - id: env
        run: |
          echo "::set-output name=env::prod"

  greet:
    runs-on: ubuntu-latest
    needs: set_environment
    steps:
      - uses: actions/checkout@v3
      - name: Show
        run: echo '${{ needs.set_environment.outputs.env }}'
