name: Manual workflow

on:
  push:
    branches:
      - release-*
      - dev-*

jobs:
  set_environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.env.outputs.env }}
    steps:
      - id: env
        run: |
          echo $GITHUB_REF_NAME
          if [[ $GITHUB_REF_NAME == release-* ]]; then
            echo "::set-output name=env::prod"
          else
            echo "::set-output name=env::dev"
          fi

  greet:
    runs-on: ubuntu-latest
    needs: set_environment
    environment: ${{ needs.set_environment.outputs.env }}
    steps:
      - uses: actions/checkout@v3
      - name: Show
        run: echo '${{ needs.set_environment.outputs.env }}'
