name: Manual workflow

on:
  pull_request:
    types: [closed]
  # workflow_dispatch:
  #   inputs:
  #     ref:
  #       description: 'branch/tag/commit id'
  #       required: true

jobs:
  set_environment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.env.outputs.env }}
    steps:
      - id: env
        run: |
          echo "::set-output name=env::prod"

  greet:
    runs-on: ubuntu-latest
    needs: set_environment
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ toJSON(github) }}'
      # - name: Show
      #   run: echo '${{ needs.set_environment.outputs.env }}'
